version: "3"
services:
  web:
    container_name: flask
    hostname: flask
    build: .
    entrypoint: gunicorn 
    command: ["--workers=3", "--bind=0.0.0.0:5000", "app:app_flask"]
    restart: always
    ports:
      - "5000:5000"
    networks:
      - default
    depends_on:
      - broker
    volumes:
      - .:/home/user/app/
  broker:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - default
  worker:
    build: .
    entrypoint: python3
    command: tasks.py
    networks:
      - default
    links:
      - broker
    depends_on:
      - broker
    volumes:
      - .:/home/user/app/
networks:
  default: